server:
  port: 8071

spring:
  application:
    name: "configserver"

  profiles:
    #active: native
    active: git

  cloud:
    config:
      server:
       # native:
         # search-locations: "classpath:/config"
         # search-locations: "file:///Users//giova//OneDrive//Documentos//config"
        git:
          uri: "https://github.com/giovanieugenio/configs-for-microservices.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "DE8354348DB78D59DCED7588C7C16"
