build:
  version: "2.0"

loans:
  message: "Welcome to GioBank loans related QAs APIs"
  contactDetails:
    name: "Marcela - QA Lead"
    email: "marcela-qa@giobank.com"
  onCallSupport:
    - (44)996452120
    - (44)102347953
